#!/bin/bash
echo "Installing..."
path="`(cd $(dirname \"$0\") && pwd )`"  # absolutized and normalized
sudo cp  $path/createCppClass /usr/local/bin
sudo chmod +x /usr/local/bin/createCppClass
echo "Done."
