#!/bin/bash
echo "Installing..."
path="`(cd $(dirname \"$0\") && pwd )`"  # absolutized and normalized
sudo cp  $path/UP /usr/local/bin/
echo -e "alias up=\". UP\"" >>  ~/.bashrc
sudo chmod +x /usr/local/bin/UP
echo "Done."
echo "You must launch \"exec bash\" command or reboot the terminal to use it."
