#!/bin/bash
echo "Installing..."
path="`(cd $(dirname \"$0\") && pwd )`"  # absolutized and normalized
sudo cp $path/calc /usr/local/bin
sudo cp $path/decToHex /usr/local/bin
sudo cp $path/hexToBin /usr/local/bin
sudo cp $path/hexToDec /usr/local/bin
sudo chmod +x /usr/local/bin/calc
sudo chmod +x /usr/local/bin/decToHex
sudo chmod +x /usr/local/bin/hexToBin
sudo chmod +x /usr/local/bin/hexToDec
echo "Done."
