#!/bin/bash
echo "Installing dependencies..."
path="`(cd $(dirname \"$0\") && pwd )`"  # absolutized and normalized
echo "path: "$path
if [ -d ~/.createNewAvrProject ]; then rm -Rf ~/.createNewAvrProject; fi
mkdir ~/.createNewAvrProject
cp -r  $path/dependencies ~/.createNewAvrProject/
sudo cp $path/createNewAvrProject /usr/local/bin
sudo chmod +x /usr/local/bin/createNewAvrProject
echo "Done."
