#!/bin/bash
echo "Installing dependencies..."
path="`(cd $(dirname \"$0\") && pwd )`"  # absolutized and normalized
if [ -d ~/.printZebraLabel ]; then rm -Rf ~/.printZebraLabel; fi
mkdir ~/.printZebraLabel
cp -r $path/dependencies ~/.printZebraLabel/
sudo cp  $path/printZebraLabel /usr/local/bin
sudo chmod +x /usr/local/bin/printZebraLabel
echo "Done."
