#!/bin/bash
echo "Removing files..."
if [ -d ~/.printZebraLabel ]; then 
	$(rm -r ~/.printZebraLabel)
fi
if [ -f /usr/local/bin/printZebraLabel ]; then 
	$(sudo rm /usr/local/bin/printZebraLabel)
fi
echo "Done."